# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 23:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderApplications',
            fields=[
                ('application_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('person_id', models.IntegerField()),
                ('max_affordability_cents', models.IntegerField()),
                ('max_affordability_currency', models.CharField(max_length=10)),
                ('expiration_date', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('vehicle_reference_id', models.CharField(max_length=200)),
                ('locked_application', django.contrib.postgres.fields.jsonb.JSONField()),
                ('threatmetrix_session_id', models.CharField(max_length=200)),
                ('partial_application', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
