# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170603_2351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Applications',
            new_name='OrderApplications',
        ),
    ]
