# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170603_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderapplications',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
