# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dataaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaudit',
            name='row_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
