# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dataaudit_row_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataAudit',
            new_name='Audit',
        ),
    ]
